ftps server was run

diff --git a/Kubernetes/server/srcs/ftps/Dockerfile b/Kubernetes/server/srcs/ftps/Dockerfile
--- a/Kubernetes/server/srcs/ftps/Dockerfile
+++ b/Kubernetes/server/srcs/ftps/Dockerfile
@@ -1,7 +1,8 @@
 FROM alpine:3.12
 
 # optionally:
-RUN apk add vim supervisor wget vsftpd openrc vsftpd-doc
+RUN apk add vim supervisor wget vsftpd openrc vsftpd-doc openssl
+RUN openssl req -x509 -nodes -days 365 -subj "/C=RU/ST=Russia/L=Kazan/O=School21/OU=21School/CN=myssl" -newkey rsa:2048 -keyout /etc/ssl/vsftpd.key -out /etc/ssl/vsftpd.crt
 
 
 # insert my configs:
@@ -13,8 +14,11 @@ COPY    srcs/start.sh /tools/start.sh
 RUN     chmod +x /tools/start.sh
 RUN     mkdir -p /run/nginx
 RUN     rc-update add vsftpd default
-# RUN     rc-service vsftpd start
+RUN     mv /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.backup
+COPY    srcs/vsftpd.conf /etc/vsftpd/vsftpd.conf
+COPY    srcs/vsftpd.userlist /etc/vsftpd/vsftpd.userlist
+# RUN     rc-service vsftpd restart || echo "Can't start"
 
-EXPOSE 21
+EXPOSE 21 30021
 
 CMD ["sh", "/tools/start.sh"]
